logger:
  level: ${LOGGER_LEVEL}

telegram:
  token: ${TELEGRAM_TOKEN}
  poller_timeout_seconds: ${TELEGRAM_POLLER_TIMEOUT_SECONDS}

postgres:
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  database: ${POSTGRES_DB}