version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./export:/var/lib/postgresql/export

  redis:
    image: redis:6.2.5
    ports:
      - "6379:6379"

volumes:
  postgres:
    driver: local
