version: '3'

silent: false

vars:
  LOCAL_BIN: "{{.USER_WORKING_DIR}}/bin"
  GOLANGCI_LINT_VERSION: v1.62.0

env:
  GOBIN: "{{.LOCAL_BIN}}"
  GOPRIVATE: "{{.GOPRIVATE}}"

tasks:
  install_golangci_lint:
    cmds:
      - "go install github.com/golangci/golangci-lint/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}"

  lint:
    deps:
      - install_golangci_lint
    cmds:
      - "{{.LOCAL_BIN}}/golangci-lint run --fix"
