CREATE TABLE IF NOT EXISTS animals (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS photos (
	id VARCHAR(255) PRIMARY KEY,
	animal_id VARCHAR(255)
	FOREIGN KEY(animal_id) REFERENCES animals(id) ON DELETE CASCADE
)